[package]
name = "rocket_empty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
schema = ["rocket_okapi", "okapi"]
default = ["schema"]

[dependencies]
rocket = { version = "=0.5.0-rc.1", default-features = false, features = ["json"] }
rocket_okapi = { git = "https://github.com/insertish/okapi", rev = "dcf0df115596ee07a587a7a543cddf3d7944645b", features = [ "swagger" ], optional = true }
okapi = { git = "https://github.com/insertish/okapi", rev = "dcf0df115596ee07a587a7a543cddf3d7944645b", optional = true }
